name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew shadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloud-sh-server.jar
          path: build/libs/cloud-sh-server*.jar
